# Generated by Django 4.1.2 on 2022-10-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.IntegerField(max_length=20)),
                ('stock', models.IntegerField()),
                ('product_image', models.TextField()),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
