# Generated by Django 4.1.2 on 2022-10-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_product_id_alter_product_code_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
